import path from "node:path";

import { execa } from "execa";
import { Node, Project, VariableDeclarationKind } from "ts-morph";

import { ESBUILD_VERSION, repoRoot } from "./helpers.ts";

const licenseUrl = `https://raw.githubusercontent.com/evanw/esbuild/v${ESBUILD_VERSION}/LICENSE.md`;
const licenseResponse = await fetch(licenseUrl);

const licenseText = await licenseResponse.text();

const commonUrl = `https://raw.githubusercontent.com/evanw/esbuild/v${ESBUILD_VERSION}/lib/shared/common.ts`;
const commonResponse = await fetch(commonUrl);

const commonText = await commonResponse.text();

const contents = `
// Code generated by scripts/vendor-esbuild; DO NOT EDIT.
// ${commonUrl}

/* eslint-disable unicorn/no-abusive-eslint-disable */
/* eslint-disable */

/*!
${licenseText.trim()}
 */

${commonText.trim()}
`.trim().replace(/\r?\n/g, "\n").trim() + "\n";

const outFile = path.resolve(repoRoot, "src", "esbuild", "third_party", "common.ts");

const project = new Project({
    tsConfigFilePath: path.resolve(repoRoot, "tsconfig.json"),
    skipAddingFilesFromTsConfig: true,
});

const sourceFile = project.createSourceFile(outFile, contents, { overwrite: true });

sourceFile.getImportDeclarationOrThrow((d) => d.getModuleSpecifierValue() === "./types")
    .setModuleSpecifier("esbuild");

sourceFile.forEachChild((node) => {
    if (Node.isFunctionDeclaration(node) && node.getNameOrThrow() === "flagsForBuildOptions") {
        node.setIsExported(true);
        return;
    }

    if (Node.isExportable(node) && node.isExported()) {
        node.setIsExported(false);
    }
});

let lastWidth: number;
do {
    lastWidth = sourceFile.getFullWidth();
    sourceFile.fixUnusedIdentifiers();
} while (lastWidth !== sourceFile.getFullWidth());

sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    declarations: [{
        name: "ESBUILD_VERSION",
        initializer: `"${ESBUILD_VERSION}"`,
    }],
});

await project.save();

await execa(path.resolve(repoRoot, "node_modules", ".bin", "dprint"), ["fmt", outFile]);
